use_frameworks!

platform :ios, '12.0'

target 'zy_encrypt_util_Example' do
  pod 'zy_encrypt_util', :path => '../'
  pod 'CryptoSwift', '1.3.3'

  target 'zy_encrypt_util_Tests' do
    inherit! :search_paths

    
  end
end
